# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_auto_20161123_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='guest', on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.User'),
            preserve_default=False,
        ),
    ]
