# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_auto_20161123_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.User'),
        ),
    ]
