# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_auto_20161123_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_type', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialnetwork.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='post',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.AddField(
            model_name='resource',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='socialnetwork.Post'),
        ),
    ]
