# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_auto_20161124_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
